import React from "react";
import { Navbar } from "@/components/layout/Navbar/Navbar";
import { Footer } from "@/components/layout/Footer/Footer";
import { Container } from "@/components/ui/Container/Container";
import { pageMetadata, siteUrl } from "@/lib/seo";
import { siteConfig } from "@/lib/site";
import {
  FileCode,
  Layers,
  ShieldCheck,
  Zap,
  ArrowRight,
  BookOpen,
  Sparkles,
  Terminal,
  RefreshCw,
} from "lucide-react";
import styles from "./OpenApiReactQuery.module.css";

export const metadata = pageMetadata({
  title: "OpenAPI to React Query | Generate Type-Safe Hooks | Reex API",
  description:
    "Convert OpenAPI and Swagger specs into production-ready TanStack React Query v5 hooks and TypeScript types. Zero boilerplate, live testing, and AST code generation.",
  path: "/openapi-react-query",
  index: true,
});

const structuredData = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebPage",
      "@id": siteUrl("/openapi-react-query#webpage"),
      url: siteUrl("/openapi-react-query"),
      name: "OpenAPI to React Query Generator | Reex API",
      description:
        "Convert OpenAPI and Swagger specifications directly into production-ready TanStack React Query v5 hooks and TypeScript types with zero boilerplate.",
      isPartOf: { "@id": `${siteConfig.marketingUrl}/#website` },
      about: { "@id": `${siteConfig.marketingUrl}/#software` },
    },
    {
      "@type": "SoftwareApplication",
      "@id": siteUrl("/openapi-react-query#software"),
      name: "Reex OpenAPI to React Query Generator",
      applicationCategory: "DeveloperApplication",
      operatingSystem: "Windows, macOS, Linux, Web",
      url: siteUrl("/openapi-react-query"),
      description:
        "Automated tool to transform OpenAPI 3.0 and 3.1 definitions into typed React Query hooks, query key factories, and API clients.",
      offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
    },
  ],
};

const sampleOpenApiCode = `// 1. Your OpenAPI Specification (YAML / JSON)
paths:
  /api/v1/users/{userId}:
    get:
      summary: Retrieve a user profile
      parameters:
        - name: userId
          in: path
          required: true
          schema: { type: string }
      responses:
        '200':
          content:
            application/json:
              schema: { $ref: '#/components/schemas/UserProfile' }

// 2. Output Generated by Reex (written to src/api-services/)
export interface UserProfile {
  id: string;
  name: string;
  email: string;
  role: "admin" | "member";
}

export const useGetUserProfileQuery = (userId: string) => {
  return useQuery({
    queryKey: usersQueryKeys.detail(userId),
    queryFn: () => usersApi.getUserProfile(userId),
    enabled: Boolean(userId),
  });
};`;

export default function OpenApiReactQueryPage() {
  return (
    <div className={styles.pageWrapper}>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(structuredData).replace(/</g, "\\u003c"),
        }}
      />
      <Navbar />
      <main className={styles.mainSection}>
        <Container>
          {/* Hero Section */}
          <div className={styles.heroContainer}>
            <div className={styles.badge}>
              <Sparkles size={14} />
              <span>OpenAPI 3.0 & 3.1 Spec Support</span>
            </div>
            <h1 className={styles.title}>
              OpenAPI to Type-Safe React Query Hooks
            </h1>
            <p className={styles.description}>
              Transform your Swagger and OpenAPI contracts into production-grade TanStack
              React Query v5 hooks, type definitions, and API clients in seconds — with
              zero runtime dependencies and zero schema drift.
            </p>
            <div className={styles.ctaGroup}>
              <a
                href={siteConfig.studioUrl}
                target="_blank"
                rel="noopener noreferrer"
                className={styles.ctaPrimary}
              >
                <span>Launch Reex Studio</span>
                <ArrowRight size={16} />
              </a>
              <a
                href={siteConfig.docsUrl}
                target="_blank"
                rel="noopener noreferrer"
                className={styles.ctaSecondary}
              >
                <BookOpen size={16} />
                <span>Read OpenAPI Guide</span>
              </a>
            </div>
          </div>

          {/* Features Grid */}
          <div className={styles.featuresGrid}>
            <div className={styles.featureCard}>
              <div className={styles.featureIconWrapper}>
                <FileCode size={20} />
              </div>
              <h2 className={styles.featureTitle}>Full OpenAPI 3.x Parsing</h2>
              <p className={styles.featureText}>
                Import OpenAPI 3.0 and 3.1 JSON or YAML specs via URL or file upload. Reex
                resolves circular references, nested schemas, and path parameters seamlessly.
              </p>
            </div>

            <div className={styles.featureCard}>
              <div className={styles.featureIconWrapper}>
                <Layers size={20} />
              </div>
              <h2 className={styles.featureTitle}>TanStack React Query v5</h2>
              <p className={styles.featureText}>
                Generates idiomatic <code>useQuery</code> and <code>useMutation</code> hooks
                complete with hierarchical query key factories and automated cache invalidation.
              </p>
            </div>

            <div className={styles.featureCard}>
              <div className={styles.featureIconWrapper}>
                <Zap size={20} />
              </div>
              <h2 className={styles.featureTitle}>AST-Powered Generation</h2>
              <p className={styles.featureText}>
                Code is synthesized using <code>ts-morph</code> and written directly to your disk
                under <code>src/api-services/</code>. No opaque wrapper libraries or runtime performance hit.
              </p>
            </div>

            <div className={styles.featureCard}>
              <div className={styles.featureIconWrapper}>
                <ShieldCheck size={20} />
              </div>
              <h2 className={styles.featureTitle}>Live In-Browser Testing</h2>
              <p className={styles.featureText}>
                Test OpenAPI endpoints directly in Reex Studio before generating code. Connect
                to your local development server with Chrome Private Network Access.
              </p>
            </div>

            <div className={styles.featureCard}>
              <div className={styles.featureIconWrapper}>
                <RefreshCw size={20} />
              </div>
              <h2 className={styles.featureTitle}>Smart Schema Diffing</h2>
              <p className={styles.featureText}>
                When backend schemas update, Reex detects added, modified, or removed endpoints
                so you can review and accept changes selectively without breaking your frontend.
              </p>
            </div>

            <div className={styles.featureCard}>
              <div className={styles.featureIconWrapper}>
                <Terminal size={20} />
              </div>
              <h2 className={styles.featureTitle}>Zero-Config CLI Bridge</h2>
              <p className={styles.featureText}>
                Run <code>npx reex-cli start</code> in your repository root to sync generated
                types and hooks straight into your Next.js or React codebase in real time.
              </p>
            </div>
          </div>

          {/* Code Preview */}
          <div className={styles.previewBlock}>
            <h2 className={styles.previewTitle}>
              From OpenAPI Schema to Typed React Query Hook
            </h2>
            <p className={styles.previewDesc}>
              No handwritten fetch calls. No outdated types. Reex parses your specification and
              writes clean, maintainable TypeScript files to your repository.
            </p>
            <pre className={styles.codePre}>
              <code>{sampleOpenApiCode}</code>
            </pre>
          </div>

          {/* Step-by-Step Instructions */}
          <div className={styles.instructionsContainer}>
            <h2 className={styles.instructionsTitle}>How It Works in 3 Simple Steps</h2>
            <div className={styles.instructionsList}>
              <div className={styles.instructionItem}>
                <span className={styles.instructionStepNumber}>1</span>
                <div>
                  <h3 className={styles.instructionHeading}>
                    Import Your OpenAPI or Swagger Spec
                  </h3>
                  <p className={styles.instructionDesc}>
                    Drag and drop your OpenAPI JSON/YAML file into{" "}
                    <a href={siteConfig.studioUrl} target="_blank" rel="noopener noreferrer" className={styles.codeInline}>
                      Reex API Studio
                    </a>{" "}
                    or paste a live schema URL. Reex parses every path, method, and schema definition instantly.
                  </p>
                </div>
              </div>

              <div className={styles.instructionItem}>
                <span className={styles.instructionStepNumber}>2</span>
                <div>
                  <h3 className={styles.instructionHeading}>
                    Test & Inspect Endpoints
                  </h3>
                  <p className={styles.instructionDesc}>
                    Verify request payloads, test localhost or staging responses, and customize
                    auth strategies (Bearer JWT or HTTP-only cookies) directly in the interactive UI.
                  </p>
                </div>
              </div>

              <div className={styles.instructionItem}>
                <span className={styles.instructionStepNumber}>3</span>
                <div>
                  <h3 className={styles.instructionHeading}>
                    Generate Production Code
                  </h3>
                  <p className={styles.instructionDesc}>
                    Run <span className={styles.codeInline}>reex start</span> in your project directory
                    to sync type definitions, query key factories, and React Query hooks directly into{" "}
                    <span className={styles.codeInline}>src/api-services/</span>.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </Container>
      </main>
      <Footer />
    </div>
  );
}
